<a href="https://colab.research.google.com/github/aryan802/kaggle_sql/blob/main/numpy_pandas_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY

NumPy (Numerical Python) provides the ndarray — a fast, fixed-type array far more efficient than Python lists for math.

In [ ]:
import numpy as np

Making Arrays

In [ ]:
# From a Python list
a = np.array([1,2,3,4,5])
print("a",a)

# Ranges
b = np.arange(0,10,2)   # [0,2,4,6,8]
print("b", b)
c = np.linspace(0,1,5)  # 5 evenly spaced from 0 to 1
print("c", c)

# Special arrays
d = np.zeros((2,3))    # 2x3 array of 0s
print(d)
e = np.ones((3,3))   # 3x3 array of 1s
print(e)
f = np.eye(3)  # 3x3 identity matrix
print(f)
g = np.random.rand(2,4)  # random floats [0,1)
print(g)

a [1 2 3 4 5]
b [0 2 4 6 8]
c [0.   0.25 0.5  0.75 1.  ]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.41585574 0.77400328 0.94696967 0.19230705]
 [0.99237792 0.85015711 0.46808175 0.8946758 ]]

Understanding array properties

In [ ]:
h = np.array([[1,2,3],[4,5,6]])
print(h)
print(h.shape) # 2 rows 3 columns
print(h.ndim)   # 2 dimensions
print(h.size)   # total elements
print(h.dtype)  # int64

# Reshaping
i = h.reshape(3,2)
print(i)
h.flatten()

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64
[[1 2]
 [3 4]
 [5 6]]

array([1, 2, 3, 4, 5, 6])

Accessing elements

In [ ]:
a = np.array([10,20,30,40,50])

print(a[0])    # first element
print(a[-1])    # last element
print(a[1:4])   # [20,30,40]
print(a[::2])   # [10,30,50]

# 2D arrays: [row, col]
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print(m[1,2])   # (row, col)
print(m[0, :])     # 1st row
print(m[:,1])     # 2nd col

# Boolean Indexing
a[a > 25]

10
50
[20 30 40]
[10 30 50]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[1 2 3]
[2 5 8]

array([30, 40, 50])

Vectorised operations (no loops needed)(elementwise operation)

NumPy applies operations element-wise automatically — this is called vectorisation and is much faster than Python loops.

In [ ]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

print(a+b)
print(a*b)
print(a**2)
print(np.round(np.sqrt(a),2))

# Aggregate functions
print(a.sum())
print(a.mean())
print(a.max())
print(np.round(a.std(),3))
print("--------")
# Axis-wise for 2D
m = np.array([[1,2],[3,4]])
print(m)
print(m.sum())        # total sum
print(m.sum(axis=0))  # sum each column
print(m.sum(axis=1))  # sum each row

[11 22 33 44]
[ 10  40  90 160]
[ 1  4  9 16]
[1.   1.41 1.73 2.  ]
10
2.5
4
1.118
--------
[[1 2]
 [3 4]]
10
[4 6]
[3 7]

PANDAS

Pandas gives you two core structures: the Series (a labelled 1D array) and the DataFrame (a labelled 2D table). Think of a DataFrame as a spreadsheet or SQL table — but programmable.

In [ ]:
import pandas as pd

Series - A labelled 1D column

In [ ]:
s = pd.Series([85,92,78,95], index = ['Alice', 'Bob', 'Carol','Dan'])
print(s)

print(s['Bob'])  # access by label
print(s[1])  # access by position
print(s[s > 90])
print(s.mean())

Alice    85
Bob      92
Carol    78
Dan      95
dtype: int64
92
92
Bob    92
Dan    95
dtype: int64
87.5

/tmp/ipykernel_4986/2036622336.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[1])  # access by position

Dataframe - A labelled 2D table

In [ ]:
data = {
    'name' : ['Alice','Bob',"Carol",'Dan'],
    'score' : [85,75,78,97],
    'grade'  : ['B','A','C','A']
}
df = pd.DataFrame(data)

print(df)
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.head(2))
print(df.tail(2))
print(df.describe())

    name  score grade
0  Alice     85     B
1    Bob     75     A
2  Carol     78     C
3    Dan     97     A
(4, 3)
Index(['name', 'score', 'grade'], dtype='object')
name     object
score     int64
grade    object
dtype: object
    name  score grade
0  Alice     85     B
1    Bob     75     A
    name  score grade
2  Carol     78     C
3    Dan     97     A
           score
count   4.000000
mean   83.750000
std     9.776673
min    75.000000
25%    77.250000
50%    81.500000
75%    88.000000
max    97.000000

loc vs iloc

In [ ]:
# select a column
print(df)
print("------------")
print(df['score'])  # returns a series
print(df[['name','score']])  # returns a dataframe

# loc - label based
print(df.loc[0])  # row with index label 0
print(df.loc[0, 'score'])
print(df.loc[1:2,['name','grade']])   # row, column
print("----------------------")
# iloc  - integer position based
print(df.iloc[0])   # first row
print(df.iloc[0,1])  # row 0, col 1
print(df.iloc[1:3, :2])  # rows 1-2, first 2 cols

# Boolean filtering
df[df['score'] > 90]  # rows where score > 90
df[df['grade'] == 'A']  # rows where grade is A

    name  score grade
0  Alice     85     B
1    Bob     75     A
2  Carol     78     C
3    Dan     97     A
------------
0    85
1    75
2    78
3    97
Name: score, dtype: int64
    name  score
0  Alice     85
1    Bob     75
2  Carol     78
3    Dan     97
name     Alice
score       85
grade        B
Name: 0, dtype: object
85
    name grade
1    Bob     A
2  Carol     C
----------------------
name     Alice
score       85
grade        B
Name: 0, dtype: object
85
    name  score
1    Bob     75
2  Carol     78

  name  score grade
1  Bob     75     A
3  Dan     97     A

Adding columns, renaming, dropping

In [ ]:
# Add a new column
df['passed'] = df['score'] >= 80
print(df)

# Rename columns
df.rename(columns={'score':'marks'}, inplace = True)  # modifies original dataframe directly
print(df)

# Drop a column
df.drop(columns=['grade'], inplace=True)
print(df)

# Drop a row by index
df.drop(index = 2, inplace = True)
print(df)

# Sort by column
df.sort_values("marks", ascending = False)
print(df)

# Reset index after dropping rows
df.reset_index(drop=True, inplace=True)
print(df)

    name  score grade  passed
0  Alice     85     B    True
1    Bob     75     A   False
2  Carol     78     C   False
3    Dan     97     A    True
    name  marks grade  passed
0  Alice     85     B    True
1    Bob     75     A   False
2  Carol     78     C   False
3    Dan     97     A    True
    name  marks  passed
0  Alice     85    True
1    Bob     75   False
2  Carol     78   False
3    Dan     97    True
    name  marks  passed
0  Alice     85    True
1    Bob     75   False
3    Dan     97    True
    name  marks  passed
0  Alice     85    True
1    Bob     75   False
3    Dan     97    True
    name  marks  passed
0  Alice     85    True
1    Bob     75   False
2    Dan     97    True

Summary statistics by group

In [ ]:
df = pd.DataFrame({
    'dept':   ['HR', 'Eng', 'HR', 'Eng', 'Eng'],
    'salary': [50000, 80000, 55000, 90000, 75000]
})

# Mean salary per department
print(df.groupby('dept')['salary'].mean())

# Multiple aggregations at once
print(df.groupby('dept')['salary'].agg(['mean', 'max', 'count']))

dept
Eng    81666.666667
HR     52500.000000
Name: salary, dtype: float64
              mean    max  count
dept
Eng   81666.666667  90000      3
HR    52500.000000  55000      2


NaN values

In [ ]:
df = pd.DataFrame({'A': [1, np.nan, 3], 'B': [4, 5, np.nan]})
df.isnull()           # True where NaN
df.isnull().sum()     # count NaNs per column

df.dropna()           # remove rows with any NaN
df.fillna(0)          # replace NaN with 0
df.fillna(df.mean())  # replace with column mean

     A    B
0  1.0  4.0
1  2.0  5.0
2  3.0  4.5

PRACTICE QUESTION

1. Create an array of integers from 1 to 20, then extract all odd numbers using boolean indexing.

In [ ]:
a = np.arange(1,21)
odds = a[a % 2 != 0]
odds

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

2. Create a 4×4 array of random integers between 0 and 100. Find the max value in each row.

In [ ]:
m = np.random.randint(0,101, size = (4,4))
print(m)
row_max = m.max(axis = 1)
col_max = m.max(axis = 0)
print(row_max)
print(col_max)

[[13 61 98 93]
 [99 33 82 72]
 [33 59 37 23]
 [52  0 84 85]]
[98 99 59 85]
[99 61 98 93]

3. Given arr = np.array([3, 1, 4, 1, 5, 9, 2, 6]), normalize it so values are between 0 and 1 (min-max normalisation).

In [ ]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
norm_arr = (arr - arr.min()) / (arr.max() - arr.min())
print(norm_arr.round(2))

[0.25 0.   0.38 0.   0.5  1.   0.12 0.62]

4. Create a 3×3 identity matrix, then multiply every element by 5.

In [ ]:
a = np.eye(5)*5
print(a)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]

5. Create a DataFrame of 5 students with columns: name, age, and score. Display only students who scored above 70.

In [ ]:
df = pd.DataFrame({
    'name':  ['Priya', 'Rohan', 'Sita', 'Arjun', 'Meera'],
    'age':   [20, 22, 21, 23, 20],
    'score': [65, 82, 74, 55, 90]
})
high_scores = df[df["score"] > 70]
print(high_scores)

    name  age  score
1  Rohan   22     82
2   Sita   21     74
4  Meera   20     90

6. Add a column called "result" that is "pass" if score ≥ 60, else "fail".

In [ ]:
df['result'] = np.where(df['score'] >= 60, 'pass', 'fail')

df['result'] = df['score'].apply(lambda x: 'pass' if x >= 60 else 'fail')
print(df)

    name  age  score result
0  Priya   20     65   pass
1  Rohan   22     82   pass
2   Sita   21     74   pass
3  Arjun   23     55   fail
4  Meera   20     90   pass

7. From the student DataFrame, find the average score grouped by age.

In [ ]:
df.groupby('age')['score'].mean()

age
20    77.5
21    74.0
22    82.0
23    55.0
Name: score, dtype: float64

8. Introduce some NaN values, then fill them with the column mean. Confirm no NaN values remain.

In [ ]:
df.loc[1, 'score'] = np.nan
df.loc[3, 'age']   = np.nan

df.fillna(df.mean(numeric_only=True), inplace=True)
print(df.isnull().sum())  # should all be 0

name     0
age      0
score    0
dtype: int64